// Code generated by protoc-gen-go. DO NOT EDIT.
// source: service.proto

package auth

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import empty "github.com/golang/protobuf/ptypes/empty"
import timestamp "github.com/golang/protobuf/ptypes/timestamp"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type CreateUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password             string   `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	FirstName            string   `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string   `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string   `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CreateUserRequest) Reset()         { *m = CreateUserRequest{} }
func (m *CreateUserRequest) String() string { return proto.CompactTextString(m) }
func (*CreateUserRequest) ProtoMessage()    {}
func (*CreateUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_5dbde6e8fba71695, []int{0}
}
func (m *CreateUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CreateUserRequest.Unmarshal(m, b)
}
func (m *CreateUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CreateUserRequest.Marshal(b, m, deterministic)
}
func (dst *CreateUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CreateUserRequest.Merge(dst, src)
}
func (m *CreateUserRequest) XXX_Size() int {
	return xxx_messageInfo_CreateUserRequest.Size(m)
}
func (m *CreateUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CreateUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CreateUserRequest proto.InternalMessageInfo

func (m *CreateUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *CreateUserRequest) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *CreateUserRequest) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *CreateUserRequest) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *CreateUserRequest) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

type GetUserRequest struct {
	Username             string   `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetUserRequest) Reset()         { *m = GetUserRequest{} }
func (m *GetUserRequest) String() string { return proto.CompactTextString(m) }
func (*GetUserRequest) ProtoMessage()    {}
func (*GetUserRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_5dbde6e8fba71695, []int{1}
}
func (m *GetUserRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetUserRequest.Unmarshal(m, b)
}
func (m *GetUserRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetUserRequest.Marshal(b, m, deterministic)
}
func (dst *GetUserRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetUserRequest.Merge(dst, src)
}
func (m *GetUserRequest) XXX_Size() int {
	return xxx_messageInfo_GetUserRequest.Size(m)
}
func (m *GetUserRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetUserRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetUserRequest proto.InternalMessageInfo

func (m *GetUserRequest) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

type User struct {
	Username             string               `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	UserId               string               `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	FirstName            string               `protobuf:"bytes,3,opt,name=first_name,json=firstName,proto3" json:"first_name,omitempty"`
	LastName             string               `protobuf:"bytes,4,opt,name=last_name,json=lastName,proto3" json:"last_name,omitempty"`
	Email                string               `protobuf:"bytes,5,opt,name=email,proto3" json:"email,omitempty"`
	Role                 string               `protobuf:"bytes,6,opt,name=role,proto3" json:"role,omitempty"`
	PasswordHash         string               `protobuf:"bytes,7,opt,name=password_hash,json=passwordHash,proto3" json:"password_hash,omitempty"`
	CreatedAt            *timestamp.Timestamp `protobuf:"bytes,8,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamp.Timestamp `protobuf:"bytes,9,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	XXX_NoUnkeyedLiteral struct{}             `json:"-"`
	XXX_unrecognized     []byte               `json:"-"`
	XXX_sizecache        int32                `json:"-"`
}

func (m *User) Reset()         { *m = User{} }
func (m *User) String() string { return proto.CompactTextString(m) }
func (*User) ProtoMessage()    {}
func (*User) Descriptor() ([]byte, []int) {
	return fileDescriptor_service_5dbde6e8fba71695, []int{2}
}
func (m *User) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_User.Unmarshal(m, b)
}
func (m *User) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_User.Marshal(b, m, deterministic)
}
func (dst *User) XXX_Merge(src proto.Message) {
	xxx_messageInfo_User.Merge(dst, src)
}
func (m *User) XXX_Size() int {
	return xxx_messageInfo_User.Size(m)
}
func (m *User) XXX_DiscardUnknown() {
	xxx_messageInfo_User.DiscardUnknown(m)
}

var xxx_messageInfo_User proto.InternalMessageInfo

func (m *User) GetUsername() string {
	if m != nil {
		return m.Username
	}
	return ""
}

func (m *User) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *User) GetFirstName() string {
	if m != nil {
		return m.FirstName
	}
	return ""
}

func (m *User) GetLastName() string {
	if m != nil {
		return m.LastName
	}
	return ""
}

func (m *User) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *User) GetRole() string {
	if m != nil {
		return m.Role
	}
	return ""
}

func (m *User) GetPasswordHash() string {
	if m != nil {
		return m.PasswordHash
	}
	return ""
}

func (m *User) GetCreatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.CreatedAt
	}
	return nil
}

func (m *User) GetUpdatedAt() *timestamp.Timestamp {
	if m != nil {
		return m.UpdatedAt
	}
	return nil
}

func init() {
	proto.RegisterType((*CreateUserRequest)(nil), "auth.CreateUserRequest")
	proto.RegisterType((*GetUserRequest)(nil), "auth.GetUserRequest")
	proto.RegisterType((*User)(nil), "auth.User")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// MyExampleServiceClient is the client API for MyExampleService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MyExampleServiceClient interface {
	CreateNewUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error)
	GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error)
}

type myExampleServiceClient struct {
	cc *grpc.ClientConn
}

func NewMyExampleServiceClient(cc *grpc.ClientConn) MyExampleServiceClient {
	return &myExampleServiceClient{cc}
}

func (c *myExampleServiceClient) CreateNewUser(ctx context.Context, in *CreateUserRequest, opts ...grpc.CallOption) (*empty.Empty, error) {
	out := new(empty.Empty)
	err := c.cc.Invoke(ctx, "/auth.MyExampleService/CreateNewUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *myExampleServiceClient) GetUser(ctx context.Context, in *GetUserRequest, opts ...grpc.CallOption) (*User, error) {
	out := new(User)
	err := c.cc.Invoke(ctx, "/auth.MyExampleService/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MyExampleServiceServer is the server API for MyExampleService service.
type MyExampleServiceServer interface {
	CreateNewUser(context.Context, *CreateUserRequest) (*empty.Empty, error)
	GetUser(context.Context, *GetUserRequest) (*User, error)
}

func RegisterMyExampleServiceServer(s *grpc.Server, srv MyExampleServiceServer) {
	s.RegisterService(&_MyExampleService_serviceDesc, srv)
}

func _MyExampleService_CreateNewUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyExampleServiceServer).CreateNewUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.MyExampleService/CreateNewUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyExampleServiceServer).CreateNewUser(ctx, req.(*CreateUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _MyExampleService_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUserRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MyExampleServiceServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/auth.MyExampleService/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MyExampleServiceServer).GetUser(ctx, req.(*GetUserRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _MyExampleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "auth.MyExampleService",
	HandlerType: (*MyExampleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateNewUser",
			Handler:    _MyExampleService_CreateNewUser_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _MyExampleService_GetUser_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "service.proto",
}

func init() { proto.RegisterFile("service.proto", fileDescriptor_service_5dbde6e8fba71695) }

var fileDescriptor_service_5dbde6e8fba71695 = []byte{
	// 372 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xb4, 0x52, 0xcf, 0x4e, 0xe2, 0x40,
	0x18, 0xa7, 0x6c, 0x29, 0xf4, 0xdb, 0x65, 0xb3, 0x3b, 0x21, 0x4b, 0x53, 0xb2, 0x91, 0xd4, 0x0b,
	0x07, 0x2d, 0x09, 0x9e, 0x3c, 0x82, 0x21, 0xea, 0x41, 0x0e, 0xa8, 0x17, 0x2f, 0xcd, 0x00, 0x1f,
	0xb4, 0x49, 0x6b, 0xeb, 0xcc, 0x54, 0xe4, 0x01, 0x7c, 0x0c, 0xdf, 0xc4, 0x87, 0x33, 0x33, 0xc3,
	0x98, 0x28, 0x89, 0x7a, 0xf1, 0x36, 0xdf, 0xef, 0x4f, 0xfb, 0xcd, 0xfc, 0x7e, 0xd0, 0xe4, 0xc8,
	0xee, 0x93, 0x39, 0x86, 0x05, 0xcb, 0x45, 0x4e, 0x6c, 0x5a, 0x8a, 0xd8, 0xef, 0xac, 0xf2, 0x7c,
	0x95, 0x62, 0x5f, 0x61, 0xb3, 0x72, 0xd9, 0xc7, 0xac, 0x10, 0x1b, 0x2d, 0xf1, 0xf7, 0xde, 0x93,
	0x22, 0xc9, 0x90, 0x0b, 0x9a, 0x15, 0x5a, 0x10, 0x3c, 0x59, 0xf0, 0xf7, 0x84, 0x21, 0x15, 0x78,
	0xcd, 0x91, 0x4d, 0xf1, 0xae, 0x44, 0x2e, 0x88, 0x0f, 0x8d, 0x92, 0x23, 0xbb, 0xa5, 0x19, 0x7a,
	0x56, 0xd7, 0xea, 0xb9, 0xd3, 0xd7, 0x59, 0x72, 0x05, 0xe5, 0x7c, 0x9d, 0xb3, 0x85, 0x57, 0xd5,
	0x9c, 0x99, 0xc9, 0x7f, 0x80, 0x65, 0xc2, 0xb8, 0x88, 0x94, 0xf3, 0x87, 0x62, 0x5d, 0x85, 0x4c,
	0xa4, 0xb5, 0x03, 0x6e, 0x4a, 0x0d, 0x6b, 0x6b, 0xaf, 0x04, 0x14, 0xd9, 0x82, 0x1a, 0x66, 0x34,
	0x49, 0xbd, 0x9a, 0x22, 0xf4, 0x10, 0x1c, 0xc0, 0xef, 0x53, 0x14, 0x5f, 0xdc, 0x2d, 0x78, 0xae,
	0x82, 0x2d, 0xb5, 0x1f, 0x5e, 0xa0, 0x0d, 0x75, 0x79, 0x8e, 0x12, 0xb3, 0xbf, 0x23, 0xc7, 0xf3,
	0x6f, 0xd8, 0x9e, 0x10, 0xb0, 0x59, 0x9e, 0xa2, 0xe7, 0x28, 0x50, 0x9d, 0xc9, 0x3e, 0x34, 0xcd,
	0x7b, 0x45, 0x31, 0xe5, 0xb1, 0x57, 0x57, 0xe4, 0x2f, 0x03, 0x9e, 0x51, 0x1e, 0x93, 0x63, 0x80,
	0xb9, 0x4a, 0x65, 0x11, 0x51, 0xe1, 0x35, 0xba, 0x56, 0xef, 0xe7, 0xc0, 0x0f, 0x75, 0x98, 0xa1,
	0x09, 0x33, 0xbc, 0x32, 0x61, 0x4e, 0xdd, 0xad, 0x7a, 0x28, 0xa4, 0xb5, 0x2c, 0x16, 0xc6, 0xea,
	0x7e, 0x6e, 0xdd, 0xaa, 0x87, 0x62, 0xf0, 0x68, 0xc1, 0x9f, 0x8b, 0xcd, 0xf8, 0x81, 0x66, 0x45,
	0x8a, 0x97, 0xba, 0x6b, 0x64, 0x04, 0x4d, 0x5d, 0x90, 0x09, 0xae, 0xd5, 0xdb, 0xb6, 0x43, 0xd9,
	0xbb, 0x70, 0xa7, 0x35, 0xfe, 0xbf, 0x9d, 0xbf, 0x8c, 0x65, 0x15, 0x83, 0x0a, 0x39, 0x84, 0xfa,
	0x36, 0x45, 0xd2, 0xd2, 0xee, 0xb7, 0xa1, 0xfa, 0xa0, 0x51, 0x09, 0x05, 0x95, 0x91, 0x73, 0xa3,
	0xaa, 0x3d, 0x73, 0xd4, 0x87, 0x8e, 0x5e, 0x02, 0x00, 0x00, 0xff, 0xff, 0x63, 0x48, 0x06, 0x89,
	0xf8, 0x02, 0x00, 0x00,
}
